### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by WOLFI3654**

### CODE REVIEW

**Comment by championballer** [comment]
@WOLFI3654 There's a grammatical error in this, please rectify that. And if you could add some screenshots or gifs, that would be great as well.

**Comment by WOLFI3654** [comment]
Can you point the error out to me?

**Comment by championballer** [comment]
_"A new sound can easily be added"_

Sorry to be pointing out such a small thing. :)

**Comment by WOLFI3654** [comment]
I think this sentence is fine. You could move the easily to the end but that is not necessary

**Comment by championballer** [comment]
@WOLFI3654 I think gifs would suit better?

**Comment by WOLFI3654** [comment]
I am sorry. I do not have the required tools to create a gif. This is the best I can give you and usually a screenshot is not a gif.

**Comment by championballer** [comment]
No issues, you can remove the screenshot then and we can merge your PR without it. Reopen this if interested. Thanks for your time. :)

**Pull request closed without merging**
